name: Epidoc-C ZIP release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the file name
        id: get_filename
        run: echo ::set-output name=filename::${GITHUB_REF#refs/tags/}.zip
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        id: create_zip
        with:
          type: 'zip'
          filename: ${{steps.get_filename.outputs.filename}}
          exclusions: '*.git*'  
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{steps.get_filename.outputs.filename}}
